### PR TITLE
Add vertex color export

### PR DESCRIPTION
**Pull request by Totchinuko**
Needed that for my project. Tested on a bunch of models painted with my own vertex painter and the export/reimport works great. Wasn't sure if I should replace missing color information with white color or just skip color export, but figured the later was better for most use case...
(I'm rather new in GitHub, hopefully I didn't failed something with this pull request)
Edit: Tested import in blender after converting into binary and it work fine too

### CODE REVIEW

**Comment by KellanHiggins** [comment]
This is looking great! What version of Unity did you do this on? Also glad you simplified the colour writing from using some crazy dictionary :D.

**Comment by Totchinuko** [comment]
hum 5.4.1f1. I plan on upgrading my whole project on 5.5 soon (and then 5.6 when stable) so I'll have to test everything.

**Comment by KellanHiggins** [comment]
I had some reports this was not working in 5.5 but haven't had time to check it out (I am still on 5.4.0). Just a warning. I bet it isn't a huge thing, probably some missing commas somewhere.

**Comment by Totchinuko** [comment]
In an ideal world, I should start working on upgrading before the end of the week... If I figure out why my builds miss some effects (a bug that drive me nuts currently :D).

**Pull request merged**
