### PR TITLE
fix not check skinnedMeshRender bug.

### PR DESCRIPTION
**Pull request by cartzhang**
if mesh have skinnedMeshRender,and if just check GetComponentsInChildren<SkinnedMeshRenderer>()
may lost some materials.

thx.

### CODE REVIEW

**Comment by cartzhang** [comment]
change MeshRender to Render so as to  contain SkinnedMeshRender

**Comment by cartzhang** [comment]
fiexed bug,if model has Skinnedmeshrender,but no Meshfilter,now can be auto add for MeshFilter.

**Comment by KellanHiggins** [comment]
Damn, you been doing work. Now excuse my incompetance, how do I merge this in? Do I just click on this big green button?

**Comment by cartzhang** [comment]
It is my pleasure.

**Comment by cartzhang** [comment]
Yes,github has merge button.
Here is what i get: https://help.github.com/articles/merging-a-pull-request/
----- 原始邮件 -----
发件人：Kellan Higgins <notifications@github.com>
收件人：KellanHiggins/UnityFBXExporter <UnityFBXExporter@noreply.github.com>
抄送人：cartzhang <cart033@sina.com>,  Author <author@noreply.github.com>
主题：Re: [KellanHiggins/UnityFBXExporter] fix not check skinnedMeshRender bug. (#20)
日期：2017年03月22日 12点09分

Damn, you been doing work. Now excuse my incompetance, how do I merge this in? Do I just click on this big green button?

&mdash;

**Comment by cartzhang** [comment]
Yes,github has merge button.
Here is what i get: https://help.github.com/articles/merging-a-pull-request/

**Comment by KellanHiggins** [comment]
Thanks! I think I merged vertex color work someone else did in. I will need to test this and then merge it in. Thanks!

**Comment by KellanHiggins** [comment]
Hmmm, looks like this is not compatible with 5.1.2. Need it to work with that. I'll need to pull in these changes and see what they screw up in 5.1.2.

**Comment by cartzhang** [comment]
Ok, my test version of unity is 5.4.0f3 and 5.4.4f1,and both them are ok.
Maybe I will test the version 5.1.2 latter.

**Comment by cartzhang** [comment]
After compare the document of  version 5.12 and later version(5.4.0 and 5.5.0),
The class ModelImporter have changed normal import mode interface.
So ,just add macro define to check version 5.1, code did not compatible with later version has been fixed.
And commit the code again.

**Comment by cartzhang** [comment]
What is more ,in my option, code did not compatible the version 5.1.2 ,the bug exist before my commit.

**Comment by KellanHiggins** [comment]
Great, I'll check this next week and merge it in. Thanks for your hard work. You rock!

**Pull request merged**
