### PR TITLE
[Update] Copy every Texture whatever it call , and Block _Color getter if null. [Add] maya get image path.

### PR DESCRIPTION
**Pull request by andysdds**
Sorry for the format style,
I made some change in
FBXUnityMaterialGetter.cs line 96 ,check that _Color is exist or not.
line 307 , it can import in Maya with correct texture path , (needed to set project first in Maya)
FBXExporter.cs line 545 , it will copy all texture in material whatever what shader is it.

Thank you your tool , great work!!

### CODE REVIEW

**Comment by andysdds** [comment]
[add] a popup windows to ask "export to Maya"

**Comment by KellanHiggins** [comment]
Tanks so much for the PR. Sorry I didn't get around to it earlier!

Unfortunately I can't pull this PR in because of the additional space after every function. But if I am to understand it correctly, it will pull in each field by the property field instead of my manual system correct?

How does the correct texture path work with Maya (I don't have access to Maya at the moment)

And awesome about copying whatever texture or material is in the shader. That is awesome!

**Comment by KellanHiggins** [comment]
Hi @andysdds, unfortunately since this is not formatted to the style of the FBX Exporter, I won't be able to accept the pullrequest.

I believe I found the code that you used,

```
for(int i = 0; i < ShaderUtil.GetPropertyCount(material.shader); i++)
{
	GetTextureUpdateMaterialWithPath(material, ShaderUtil.GetPropertyName(material.shader, i), newPath);
}
```

However, I am getting errors thrown when I try and use that. 

But this seemed to work.
```
string[] textures = material.GetTexturePropertyNames();
for(int i = 0, l = textures.Length; i < l; i++)
{
	GetTextureUpdateMaterialWithPath(material, textures[i], newPath);
}
```

Thanks for making this pull request by the way. Took me three years to get to it but it was very helpful!

**Comment by KellanHiggins** [comment]
I figured this out (just testing) used some other code to pull in every texture and makes sure duplicates aren't created. Thanks for putting me onto this, this is a really awesome fix.

**Pull request closed without merging**
